### ISSUE TITLE
ROCm container not working

### ISSUE THREAD

**Issue by BSchilperoort** [haddocking/powerfit#49]
I tried to run the container image for powerfit using ROCm. However, it breaks on a missing argument when the code tries to call `CPUCorrelator.scan`;

```
> sudo docker run --rm -ti
>     --device=/dev/kfd --device=/dev/dri
>     --security-opt seccomp=unconfined
>     --group-add video --ipc=host
>     -v $PWD/data:/data ghcr.io/haddocking/powerfit-rocm:v3.0.3
>     /data/ribosome-KsgA.map 13 data/KsgA.pdb
>     -a 20 -p 2 -l -d /data/run-KsgA-docker-amd--gpu

Target file read from: /data/ribosome-KsgA.map                                                                                                                                                                       
Target resolution: 13.00                                                                                                                                                                                             
Initial shape of density: 128 128 128                                                                                                                                                                                
Shape after trimming: 60 73 67                                                                                                                                                                                       
Shape after extending: 60 75 70                                                                                                                                                                                      
Template file read from: /data/KsgA.pdb                                                                                                                                                                              
Reading in rotations.                                                                                                                                                                                                
Requested rotational sampling density: 20.00                                                                                                                                                                         
Real rotational sampling density: 20.83                                                                                                                                                                              
Requested number of processors: 2                                                                                                                                                                                    
Starting search                                                                                                                                                                                                      
Processing rotations   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/648  [ 0:00:00 < -:--:-- , ? rot/s ]Process Process-1:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/powerfit_em/powerfitter.py", line 151, in _run_correlator_instance
    correlator.scan()
  File "/usr/local/lib/python3.12/site-packages/powerfit_em/powerfitter.py", line 151, in _run_correlator_instance
    correlator.scan()
TypeError: CPUCorrelator.scan() missing 1 required positional argument: 'progress'
TypeError: CPUCorrelator.scan() missing 1 required positional argument: 'progress'
```

**Comment by BSchilperoort** [comment]
Also occurs running it directly, on `master`.

Bug seems to have been introduced in 75fe752038a43aeb96c1d513fbf7eecb2098e7b2
(adding the argument `progress` to `CPUCorrelator.scan()`, without a default value).

**Comment by sverhoeven** [comment]
Your made a typo `/data/run-KsgA-docker-amd--gpu` should be `/data/run-KsgA-docker-amd --gpu`.

Still the error happens when you use more than 1 cpu processor (`-p 2`).

**Comment by BSchilperoort** [comment]
> Your made a typo `/data/run-KsgA-docker-amd--gpu` should be `/data/run-KsgA-docker-amd --gpu`.

I copy pasted from the README. The docker command there says `/data/run-KsgA-docker-amd--gpu`  (no space)
